version: "3.8"
name: "Book-Store-Spring-Boot-Microservices"
services:
  catalog-service:
    image: muhhhammad/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
       catalog-db:
         condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m