name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      working-directory: ./catalog-service

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable (Linux only)
        if: runner.os == 'Linux'
        run: chmod +x mvnw

      - name: Build with Maven (Linux)
        if: runner.os == 'Linux'
        run: ./mvnw -ntp verify

      - name: Build with Maven (Windows)
        if: runner.os == 'Windows'
        run: .\mvnw.cmd -ntp verify


#        - if: #{{ github.ref == 'refs/heads/main' }}